[tool.poetry]
name = "globalise-tools"
version = "0.1.0"
description = ""
authors = ["Bram Buitendijk <bram.buitendijk@di.huc.knaw.nl>"]
readme = "README.md"
packages = [{ include = "globalise_tools" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
dataclasses-json = "^0.5.7"
jsondataclass = "^0.3.0"
#pagexml-tools = {path = "/Users/bram/workspaces/pagexml", develop = true}
pagexml-tools = "^0.2.1"
spacy = {extras = ["apple"], version = "^3.4.3"}
tabulate = "^0.9.0"
textrepo-client = "^0.5.1"
xlsxwriter = "^3.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
