[tool.poetry]
name = "globalise-tools"
version = "0.1.0"
description = ""
authors = ["Bram Buitendijk <bram.buitendijk@di.huc.knaw.nl>"]
readme = "README.md"
packages = [{ include = "globalise_tools" }]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
annorepo-client = { path = "/Users/bram/workspaces/elucidate/annorepo-client", develop = true }
#annorepo-client = "^0.5.1"
dataclasses-json = "^0.5.7"
icecream = "^2.1.3"
jsondataclass = "^0.3.0"
loguru = "^0.6.0"
#pagexml-tools = {path = "/Users/bram/workspaces/pagexml", develop = true}
pagexml-tools = "^0.2.1"
spacy = { extras = ["apple"], version = "^3.4.3" }
stam = "^0.0.2"
tabulate = "^0.9.0"
textrepo-client = "^0.5.1"
uuid = "^1.30"
xlsxwriter = "^3.0.3"
colorama = "^0.4.6"
blessedtable = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
