[tool.poetry]
name = "globalise-tools"
version = "0.1.0"
description = ""
authors = ["Bram Buitendijk <bram.buitendijk@di.huc.knaw.nl>"]
readme = "README.md"
packages = [{ include = "globalise_tools" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pagexml-tools = {path = "/Users/bram/workspaces/pagexml", develop = true}
tabulate = "^0.9.0"
xlsxwriter = "^3.0.3"
jsondataclass = "^0.3.0"
dataclasses-json = "^0.5.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
