[tool.poetry]
name = "globalise-tools"
version = "0.1.0"
description = ""
authors = ["Bram Buitendijk <bram.buitendijk@di.huc.knaw.nl>"]
readme = "README.md"
packages = [{ include = "globalise_tools" }]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"

#annorepo-client = "^0.5.1"
annorepo-client = { path = "/Users/bram/workspaces/annorepo/annorepo-client", develop = true }

#textrepo-client = "^0.5.1"
textrepo-client = { path = "/Users/bram/workspaces/textrepo/textrepo-client-python", develop = true }

#pagexml-tools = "^0.3.3"
pagexml-tools = { path = "/Users/bram/workspaces/pagexml", develop = true }

blessedtable = "^1.0.0"
colorama = "^0.4.6"
dataclasses-json = "^0.5.7"
dkpro-cassis = "^0.7.6"
icecream = "^2.1.3"
jsondataclass = "^0.3.0"
loguru = "^0.7.0"
pycaprio = "^0.2.1"
spacy = { extras = ["apple"], version = "^3.4.3" }
stam = "^0.2.2"
tabulate = "^0.9.0"
uuid = "^1.30"
xlsxwriter = "^3.0.3"
hydra-core = "^1.3.2"
appengine-python-standard = "^1.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
